- hosts: localhost
  become: true
  vars_files:
    - vars/default.yml
    
  tasks:
    # 
    #- name: Update apt cache
    #  apt:
    #    update_cache: yes

    - name: Install Apache, MySQL, PHP, and other dependencies
      apt:
        name:
          - git
          - apache2
          - python3-pymysql
          - mysql-client
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    
    - name: host root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: virtualhost
      template:
        src: "files/apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: разрешить сайт
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: отключить страничку Apache по умолчанию
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache
      
    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: mySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: удалить тестовую базу
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
        
    - name: создать БД
      mysql_db:
        name: ipcount
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
    
    - name: и таблицу в ней
      mysql_query:
        login_db: ipcount
        login_user: root
        login_password: "{{ mysql_root_password }}"
        query:
          - create table iplist (id INT UNSIGNED NOT NULL AUTO_INCREMENT,ipa VARCHAR (50),kol int, PRIMARY KEY (id))
        single_transaction: true  
              
    - name: поставить страничку свою
      template:
        src: "files/info.php"
        dest: "/var/www/{{ http_host }}/info.php"
    
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
